### ISSUE TITLE
Sending Tokens to other accounts but can't withdraw Tokens !

### ISSUE THREAD

**Issue by BTCLottery** [loomnetwork/token-gateway-example#1]
Hi,

I'm trying to understand how the Token Transfer Gateway works and while testing, i stumbled upon a few bugs,  and stuff that I can't currently even grasp. 

When trying to move tokens around from acounts[0] to account[2] etc, the tokens appear fine in all cases when you deposit, but for some reason you are not allowed to withdraw using the gateway, either not part of the validated user list or maybe BigNumber balance error in React.

 - Tried to deposit the 999.999.900 left from the owner accounts[0] but when i withdraw i get a balance of 1e47 and can't press the withdraw button
 - Tried to send 100 tokens from accounts[0] to accounts[2], it receives the Token but when I try to deposit the token, i don't see 100 Tokens i see 100000000000000000000 and can't withdraw the amount from the gateway
 - Sent from accounts[0] 1000 GTK Tokens to accounts[2] , after depositing the amount from accounts[2], get the same BigNumber error of 1e47.. and can't withdraw the sum from the gateway...

Keep up the amazing work and thank you in advance for clarifying the way token-gateway-example works.

**Comment by mikedeshazer** [comment]
I will try to reproduce the bug. From my experience though, I'm going to assume this has something to do with decimals in the token smart contract, based on your description of the problem.

**Comment by eduardonunesp** [comment]
Thank you @BTCLottery  and @mikedeshazer  for the reports, right now, this repo is outdated and please move to `https://github.com/loomnetwork/transfer-gateway-example` which is the most up to date stuff about Loom's Transfer Gateway
